finish working out kinks in CLI

diff --git a/candy_machine_setup b/candy_machine_setup
--- a/candy_machine_setup
+++ b/candy_machine_setup
@@ -48,6 +48,7 @@ cmm_dir=''
 env_ex_file=''
 env_file=''
 num_imgs=''
+distro=''
 
 ## FUNCTIONS
 help_print() { # print help text
@@ -76,20 +77,15 @@ err_print() { # error print
 }
 
 success_printf() { # printf implementation of success print
-   spacer="$1"
-   output="$2"
-   printf "${green}%$((${COLUMNS} - ${#spacer}))s\n${normal}" "${output}"
+   printf "\r\033[K${green}%s\n${normal}" "$*"
 }
 
 warn_printf() { # printf impementation of warning print
-   output="$1"
-   printf "${orange}%s${normal}" "${output}"
+   printf "\r\033[K${orange}%s${normal}" "$*"
 }
 
 err_printf() { # printf impementation of error print
-   spacer="$1"
-   output="$2"
-   printf "${red}%$((${COLUMNS} - ${#spacer}))s\n${normal}" "${output}"
+   printf "\r\033[K${red}%s\n${normal}" "$*"
 }
 
 shutdown() { # reset cursor in case spinner command errors out
@@ -103,13 +99,11 @@ cursorBack() { # move cursor back for spinner animation
 
 spinner() { # spiner animation so user doesn't think script is hung
     local LC_TYPE=C
-    local info="$1"
     local pid=$!
     local delay=0.1
-    local spin='⣾⣽⣻⢿⡿⣟⣯⣷'
-    #local spin='◐◓◑◒'
+    #local spin='⣾⣽⣻⢿⡿⣟⣯⣷'
+    local spin='◐◓◑◒'
     local charwidth=1
-    printf "$info"
 
     local i=0
     tput civis # invisible cursor
@@ -129,7 +123,7 @@ spinner() { # spiner animation so user doesn't think script is hung
 
 check_cmd() { # check if command failed
    if [ $1 -ne 0 ]; then
-      err_printf "$2" "$3"
+      err_printf "$2"
       exit 13
    fi
 }
@@ -148,15 +142,15 @@ need_arg() { # flag that no argument was passed with long flag
 }
 
 check_npm_installed() { # check if specified npm package is installed
-   echo "Checking to see if [$1] is installed..."
+   printf "Checking to see if [$1] is installed..."
    npm list -g | grep -q $1
 }
 
 install_npm_pkg() { # install npm package quietly
    warn_printf "[$1] not found, installing..."
    sudo npm install -g $1 &>/dev/null
-   check_cmd $? "[$1] not found, installing..." "[failed to install $1]"
-   success_printf "[$1] not found, installing..." "[$1] installed successfully"
+   check_cmd $? "[failed to install $1]"
+   success_printf "[$1] installed successfully"
 }
 
 check_installed() { # check if package is installed
@@ -167,14 +161,20 @@ check_installed() { # check if package is installed
 install_pkg() { # install package quietly
    warn_printf "[$1] not found, installing..."
    sudo apt-get update -qq
-   sudo DEBIAN_FRONTEND=noninteractive apt-get install -qq $1 &>/dev/null
-   check_cmd $? "[$1] not found, installing..." "[failed to install $1]"
-   success_printf "[$1] not found, installing..." "[$1] installed successfully"
+   sudo apt-get install -qq $1 &>/dev/null
+   check_cmd $? "[failed to install $1]"
+   success_printf "[$1] installed successfully"
 }
 
 string_contains() { # check if substring ($1) in string ($2), case insensitve search
    local _lc=${2,,}
    [ -z "$1" ] || { [ -z "${_lc##*${1,,}*}" ] && [ -n "$2" ] ;} ;
+}
+
+check_alt() {
+    if [ "X${distro}" == "X${1}" ]; then
+        distro="${2}"
+    fi
 }
 
 ## USER INPUT
@@ -215,53 +215,145 @@ fi
 ## MAIN SCRIPT
 current_dir=$(pwd) # save current working directory
 log_file="${current_dir}/candy_machine_setup_error.log"
-# check if 'nodejs' is setup, install if not
-current_display="Checking to see if [nodejs] is installed..."
-printf "${current_display}"
-if node --version &>/dev/null; then
-   success_printf "${current_display}" "[nodejs found]"
+
+`sudo apt-update &>/dev/null` # just to prompt for sudo password upfront
+
+# install pre-requisites
+if check_installed curl; then
+   success_printf "[curl] found."
 else
-   printf "\n"
-   if check_installed curl; then
-      success_printf "Checking to see if [curl] is installed..." "[curl] found."
-   else
-      install_pkg curl
+   install_pkg curl
+fi
+
+if check_installed gcc; then
+   success_printf "[gcc] found."
+else
+   install_pkg gcc
+fi
+
+if check_installed g++; then
+   success_printf "[g++] found."
+else
+   install_pkg g++
+fi
+
+if check_installed make; then
+   success_printf "[make] found."
+else
+   install_pkg make
+fi
+
+if check_installed apt-transport-https; then
+   success_printf "[apt-transport-https] found."
+else
+   install_pkg apt-transport-https
+fi
+
+if check_installed lsb-release; then
+   success_printf "[lsb-release] found."
+else
+   install_pkg lsb-release
+fi
+
+if check_installed gnupg; then
+   success_printf "[gnupg] found."
+else
+   install_pkg gnupg
+fi
+
+# check if 'nodejs' is setup, install if not
+printf "Checking to see if [nodejs] installed..."
+if node --version &>/dev/null; then
+   success_printf "[nodejs found]"
+else
+   node_repo="node_16.x"
+   distro=$(lsb_release -c -s)
+
+   check_alt "solydxk-9"       "stretch"
+   check_alt "sana"            "jessie"
+   check_alt "kali-rolling"    "bullseye"
+   check_alt "Tyche"           "stretch"
+   check_alt "Nibiru"          "buster"
+   check_alt "Horizon"         "stretch"
+   check_alt "Continuum"       "stretch"
+   check_alt "patito feo"      "buster"
+   check_alt "maya"            "precise"
+   check_alt "qiana"           "trusty"
+   check_alt "rafaela"         "trusty"
+   check_alt "rebecca"         "trusty"
+   check_alt "rosa"            "trusty"
+   check_alt "sarah"           "xenial"
+   check_alt "serena"          "xenial"
+   check_alt "sonya"           "xenial"
+   check_alt "sylvia"          "xenial"
+   check_alt "tara"            "bionic"
+   check_alt "tessa"           "bionic"
+   check_alt "tina"            "bionic"
+   check_alt "tricia"          "bionic"
+   check_alt "ulyana"          "focal"
+   check_alt "ulyssa"          "focal"
+   check_alt "uma"             "focal"
+   check_alt "betsy"           "jessie"
+   check_alt "cindy"           "stretch"
+   check_alt "debbie"          "buster"
+   check_alt "luna"            "precise"
+   check_alt "freya"           "trusty"
+   check_alt "loki"            "xenial"
+   check_alt "juno"            "bionic"
+   check_alt "hera"            "bionic"
+   check_alt "odin"            "focal"
+   check_alt "toutatis"        "precise"
+   check_alt "belenos"         "trusty"
+   check_alt "flidas"          "xenial"
+   check_alt "etiona"          "bionic"
+   check_alt "lugalbanda"      "xenial"
+   check_alt "anokha"          "wheezy"
+   check_alt "anoop"           "jessie"
+   check_alt "drishti"         "stretch"
+   check_alt "unnati"          "buster"
+   check_alt "bunsen-hydrogen" "jessie"
+   check_alt "helium"          "stretch"
+   check_alt "lithium"         "buster"
+   check_alt "chromodoris"     "jessie"
+   check_alt "green"           "sid"
+   check_alt "amber"           "buster"
+   check_alt "jessie"          "jessie"
+   check_alt "ascii"           "stretch"
+   check_alt "beowulf"         "buster"
+   check_alt "ceres"           "sid"
+   check_alt "panda"           "sid"
+   check_alt "unstable"        "sid"
+   check_alt "stable"          "buster"
+   check_alt "onyedi"          "stretch"
+   check_alt "lemur-3"         "stretch"
+   check_alt "orel"            "stretch"
+   check_alt "dolcetto"        "stretch"
+
+   if [ -f "/etc/apt/sources.list.d/chris-lea-node_js-$distro.list" ]; then # remove Launchpad PPA repo, if found
+      $(sudo add-apt-repository -y -r ppa:chris-lea/node.js)
+      $(sudo rm -f /etc/apt/sources.list.d/chris-lea-node_js-${distro}.list)
    fi
 
-   curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
+   keyring='/usr/share/keyrings'
+   local_node_key="$keyring/nodesource.gpg"
 
-   # install pre-requisites
-   if check_installed gcc; then
-      success_printf "Checking to see if [gcc] is isntalled..." "[gcc] found."
-   else
-      install_pkg gcc
-   fi
+   curl -s "https://deb.nodesource.com/gpgkey/nodesource.gpg.key" | gpg --dearmor | sudo tee $local_node_key >/dev/null
 
-   if check_installed g++; then
-      success_printf "Checking to see if [g++] is isntalled..." "[g++] found."
-   else
-      install_pkg g++
-   fi
-
-   if check_installed make; then
-      success_printf "Checking to see if [make] is isntalled..." "[make] found."
-   else
-      install_pkg make
-   fi
-   
+   echo "deb [signed-by=$local_node_key] https://deb.nodesource.com/${node_repo} ${distro} main" | sudo tee /etc/apt/sources.list.d/nodesource.list
+   echo "deb-src [signed-by=$local_node_key] https://deb.nodesource.com/${node_repo} ${distro} main" | sudo tee -a /etc/apt/sources.list.d/nodesource.list
    install_pkg nodejs
 fi
 
 # check if 'yarn' is installed, install if not
 if check_npm_installed yarn; then
-   success_printf "Checking to see if [yarn] is isntalled..." "[yarn] found."
+   success_printf "[yarn] found."
 else
    install_npm_pkg yarn
 fi
 
 # check if 'git' is installed, install if not
 if check_installed git; then
-   success_printf "Checking to see if [git] is isntalled..." "[git] found."
+   success_printf "[git] found."
 else
    install_pkg git
 fi
@@ -269,38 +361,40 @@ fi
 # clone metaplex repo
 if [ ! -d "${current_dir}/metaplex" ]; then # only clone if not already existing
    printf "cloning [metaplex] repo..."
-   git clone https://github.com/metaplex-foundation/metaplex.git &>/dev/null
-   check_cmd $? "cloning [metaplex] repo..." "failed to clone [metaplex] repo."
-   success_printf "cloning [metaplex] repo..." "[metaplex] repo cloned successfully."
+   git clone https://github.com/metaplex-foundation/metaplex.git &>/dev/null &
+   spinner
+   check_cmd $? "failed to clone [metaplex] repo."
+   success_printf "[metaplex] repo cloned successfully."
 fi
 
 # check if 'ts-node' installed, install if not
 if check_npm_installed ts-node; then
-   success_printf "Checking to see if [ts-node] is isntalled..." "[ts-node] found."
+   success_printf "[ts-node] found."
 else
    install_npm_pkg ts-node
 fi
 
 # check if solana is installed, install if not
-echo "Checking to see if [solana] installed..."
+printf "Checking to see if [solana] installed..."
 if solana --version &>/dev/null; then
-   success_printf "Checking to see if [solana] is isntalled..." "[solana] found."
+   success_printf "[solana] found."
 else
-   warn_print "[solana] not found, installing..."
-   sh -c "$(curl -sSfL https://release.solana.com/v1.8.0/install)"
-   check_cmd $? "[solana] not found, installing..." "failed to install [solana]"
+   warn_printf "[solana] not found, installing..."
+   sh -c "$(curl -sSfL https://release.solana.com/v1.8.0/install)" &>/dev/null &
+   spinner
+   check_cmd $? "failed to install [solana]"
    . ~/.profile # source .profile so PATH updates in current session
-   success_printf "[solana] not found, installing..." "[solana] installed successfully."
+   success_printf "[solana] installed successfully."
 fi
 
 solana config set --url https://api.${network}.solana.com >/dev/null # set solana network
-check_cmd $?
+check_cmd $? "unable to set Solana network"
 keyJSON="${HOME}/.config/solana/wallet.json"
 
 if [ ! -f $keyJSON ]; then # only if keypair doesn't exist
    if [ "${pubkey}" = "new" ]; then # generate new wallet
       solana-keygen new --outfile $keyJSON > tmp.txt
-      check_cmd $?
+      check_cmd $? "unable to create wallet"
 
       pubkey=$(cat tmp.txt | grep pubkey | cut -d' ' -f2)
       passphrase=$(cat tmp.txt | grep -A 1 recover | grep -v recover)
@@ -309,19 +403,19 @@ if [ ! -f $keyJSON ]; then # only if keypair doesn't exist
       echo "Save this seed phrase and your BIP39 passphrase to recover your new keypair: [${passphrase}]."
       read -r -s -N 1 -p "Press [Enter] to continue..."
    else  #import public wallet
-      echo "${orange}Note: You will need your recovery phrase to import wallet. This is required by Solana CLI and will not be saved by this script nor on the system anywhere. The input is silent as well so no one can see the input as you type it in or copy it!${normal}"
+      echo "${orange}Note: You will need your recovery phrase to import wallet. This is required by Solana CLI and will not be saved by this script nor on the system anywhere. The input is silent as well so no one can see the input as you type it in or paste it!${normal}"
       solana-keygen recover 'prompt://?key=0/0' --outfile $keyJSON
-      check_cmd $? "" "failed to import wallet."
+      check_cmd $? "failed to import wallet."
    fi
 fi
 
 solana config set --keypair $keyJSON >/dev/null # set Solana CLI to use wallet
-check_cmd $?
+check_cmd $? "unable to set keypair"
 success_print "set keypair successfully."
 
 if [ "${network}" = "devnet" ]; then # only airdrop if running on devnet
-   solana airdrop 1 >/dev/null #airdrop some SOL
-   check_cmd $? "" "airdrop to wallet failed."
+   solana airdrop 1 &>/dev/null #airdrop some SOL
+   check_cmd $? "airdrop to wallet failed."
    success_print "airdropped 1 SOL."
 fi
 
@@ -331,57 +425,61 @@ assets_dir="${current_dir}/assets"
 if [ ! -d $assets_dir ]; then # only if directory doesn't exist
    printf "Creating directory for images..."
    mkdir $assets_dir &>/dev/null # create directory for assests
-   check_cmd "Creating directory for images..." "failed to create [$assets_dir}]."
-   success_printf "Creating directory for images..." "Directory [${assets_dir}] created successfully."
+   check_cmd $? "failed to create [$assets_dir}]."
+   success_printf "Directory [${assets_dir}] created successfully."
 fi
 
 js_dir="${metaplex_dir}/js"
 cd $js_dir
 
-echo "" # just adding an extra break in output
-echo "Installing node modules..."
-yarn install --silent 2>${log_file} # install required npm modules
-check_cmd $? "Installing node modules..." "failed to install node modules."
-success_printf "Installing node moudles..." "Node modules installed successfully."
+printf "Installing node modules..."
+yarn install --silent 2>${log_file} & # install required npm modules
+spinner
+check_cmd $? "failed to install node modules."
+success_printf "Node modules installed successfully."
 
 echo "${orange}********************************************************************************************************************************************
 Pausing to allow time to upload images and JSON files to [${assets_dir}]. Refer to the README for further
 information on properly setting up your images and JSON files.
-}*******************************************************************************************************************************************${normal}"
+********************************************************************************************************************************************${normal}"
 read -r -s -N 1 -p "Press [Enter] to continue..." key
+echo ""
 
 cd ${current_dir} # go back to starting location to save mint cache there
 cm_cli="${js_dir}/packages/cli/src/candy-machine-cli.ts"
 
 printf "Uploading images for candy machine..."
-ts-node $cm_cli upload $assets_dir --env ${network} --keypair ${keyJSON} 2>${log_file} 1>/dev/null
-check_cmd $? "Uploading images for candy machine..." "failed to upload images."
-success_printf "Uploading images for candy machine..." "Image upload successful."
+ts-node $cm_cli upload $assets_dir --env ${network} --keypair ${keyJSON} 2>${log_file} 1>/dev/null &
+spinner
+check_cmd $? "failed to upload images."
+success_printf "Image upload successful."
 
-sol_price=$(curl https://www.coingecko.com/en/coins/solana 2>/dev/null | grep -oP '(?<=<span class="no-wrap" data-price-btc).*?(?=</span>)' | sed 's/[^>]*>//g' | sed -n '1p')
-
-read -p "What would you like the price of the NFTs to be (in SOL [1 SOL currently ${sol_price} USD]): " price
+read -p "What would you like the price of the NFTs to be (in SOL): " price
 
 printf "Creating candy machine..."
-ts-node $cm_cli create_candy_machine --env ${network} --keypair ${keyJSON} --price ${price} 2>${log_file} 1>/dev/null
-check_cmd $? "Creating candy machine..." "failed to create candy machine."
-success_printf "Creating candy machine..." "Candy machine created successfully."
+ts-node $cm_cli create_candy_machine --env ${network} --keypair ${keyJSON} --price ${price} 2>${log_file} 1>/dev/null &
+spinner
+check_cmd $? "failed to create candy machine."
+success_printf "Candy machine created successfully."
 
 start_of_today=`date '+%d %b %Y 00:00:00 %Z'`
 printf "Updating candy machine with available minting start date to [${start_of_today}]..."
-ts-node $cm_cli update_candy_machine --env ${network} --keypair ${keyJSON} --date "${start_of_today}" 2>${log_file} 1>/dev/null
-check_cmd $? "Updating candy machine with available minting start date to [${start_of_today}]..." "failed to update candy machine."
-success_printf "Updating candy machine with available minting start date to [${start_of_today}]..." "Date updated successfully."
+ts-node $cm_cli update_candy_machine --env ${network} --keypair ${keyJSON} --date "${start_of_today}" 2>${log_file} 1>/dev/null &
+spinner
+check_cmd $? "failed to update candy machine."
+success_printf "Date updated successfully."
 
-num_imgs=$(ls ${assests_dir}/*.png | wc -l) # get number of images in assets directory
+num_imgs=$((`ls ${assets_dir} | wc -l` / 2 )) # get number of images in assets directory
 count=0 # used in progress print
 
-for i in $(seq $num_images); do # mint images, one at a time
-   printf "\rMinting operation ongoing... successfully minted [${count}] of [${num_imgs}]"
-   ts-node $cm_cli mint_one_token -e ${network} -k ${keyJSON} 2>${log_file} 1>/dev/null
-   check_cmd $? "Minting operation ongoing... successfully minted [${count}] of [${num_imgs}]" "unable to mint image."
+for i in $(seq $num_imgs); do # mint images, one at a time
+   printf "\rMinting operation ongoing... successfully minted [${count}/${num_imgs}]..."
+   ts-node $cm_cli mint_one_token -e ${network} -k ${keyJSON} 2>${log_file} 1>/dev/null &
+   spinner
+   check_cmd $? "unable to mint image."
    count=$((count+1))
 done
-success_print "\r[${count}] images successfully minted."
+printf "\r\033[K" # return cursor to beginning and clear
+success_print "[${count}] images successfully minted."
 
 exit 0 # normal exit
