change mint method from candy machine UI to CLI

diff --git a/candy_machine_setup b/candy_machine_setup
--- a/candy_machine_setup
+++ b/candy_machine_setup
@@ -8,8 +8,6 @@
 # Description:                                                        #
 # This script sets up a metaplex store and candy machine for batch    #
 # minting from scratch.                                               #
-#                                                                     #
-# NOTE: this script must NOT be run as root!                          #
 #######################################################################
 
 if [ `whoami` = root ]; then # exit if running as root
@@ -46,12 +44,10 @@ metaplex_dir=''
 assets_dir=''
 js_dir=''
 cm_cli=''
-cm_publickey=''
-cm_pubkey=''
-cm_timestamp=''
 cmm_dir=''
 env_ex_file=''
 env_file=''
+num_imgs=''
 
 ## FUNCTIONS
 help_print() { # print help text
@@ -80,14 +76,22 @@ err_print() { # error print
 }
 
 success_printf() { # printf implementation of success print
-   arr=("$@")
-   printf "${green}[%$((${COLUMNS} - ${#arr[0]} + 11))s]\n${normal}" "${arr[1]}"
+   spacer="$1"
+   output="$2"
+   printf "${green}%$((${COLUMNS} - ${#spacer}))s\n${normal}" "${output}"
+}
+
+warn_printf() { # printf impementation of warning print
+   output="$1"
+   printf "${orange}%s${normal}" "${output}"
 }
 
 err_printf() { # printf impementation of error print
-   arr=("$@")
-   printf "${red}[%$((${COLUMNS} - ${#arr[0]} + 11))s]\n${normal}" "${arr[1]}"
+   spacer="$1"
+   output="$2"
+   printf "${red}%$((${COLUMNS} - ${#spacer}))s\n${normal}" "${output}"
 }
+
 shutdown() { # reset cursor in case spinner command errors out
     tput cnorm # reset cursor
 }
@@ -112,7 +116,7 @@ spinner() { # spiner animation so user doesn't think script is hung
 
     while kill -0 $pid 2> /dev/null; do
 	    local i=$(((i + $charwidth) % ${#spin}))
-	    printf "${green}%s${normal}" "${spin:$i:$charwidth}"
+	    printf "${cyan}%s${normal}" "${spin:$i:$charwidth}"
 	    
         cursorBack $charwidth
 	    sleep $delay
@@ -125,7 +129,7 @@ spinner() { # spiner animation so user doesn't think script is hung
 
 check_cmd() { # check if command failed
    if [ $1 -ne 0 ]; then
-      err_print "Fatal error!"
+      err_printf "$2" "$3"
       exit 13
    fi
 }
@@ -149,23 +153,23 @@ check_npm_installed() { # check if specified npm package is installed
 }
 
 install_npm_pkg() { # install npm package quietly
-   warn_print "[$1] not found, installing..."
+   warn_printf "[$1] not found, installing..."
    sudo npm install -g $1 &>/dev/null
-   check_cmd $?
-   success_print "[$1] installed successfully"
+   check_cmd $? "[$1] not found, installing..." "[failed to install $1]"
+   success_printf "[$1] not found, installing..." "[$1] installed successfully"
 }
 
 check_installed() { # check if package is installed
-   echo "Checking to see if [$1] is installed..."
+   printf "Checking to see if [$1] is installed..."
    apt -qq list $1 2>/dev/null | grep -qE "(installed|upgradable)"
 }
 
 install_pkg() { # install package quietly
-   warn_print "[$1] not found, installing..."
+   warn_printf "[$1] not found, installing..."
    sudo apt-get update -qq
-   sudo DEBIAN_FRONTEND=noninteractive apt-get install -qq $1 >/dev/null
-   check_cmd $?
-   success_print "[$1] installed successfully"
+   sudo DEBIAN_FRONTEND=noninteractive apt-get install -qq $1 &>/dev/null
+   check_cmd $? "[$1] not found, installing..." "[failed to install $1]"
+   success_printf "[$1] not found, installing..." "[$1] installed successfully"
 }
 
 string_contains() { # check if substring ($1) in string ($2), case insensitve search
@@ -210,13 +214,16 @@ fi
 
 ## MAIN SCRIPT
 current_dir=$(pwd) # save current working directory
+log_file="${current_dir}/candy_machine_setup_error.log"
 # check if 'nodejs' is setup, install if not
-echo "Checking to see if [nodejs] is installed..."
+current_display="Checking to see if [nodejs] is installed..."
+printf "${current_display}"
 if node --version &>/dev/null; then
-   echo "${green}[nodejs] found.${normal}"
+   success_printf "${current_display}" "[nodejs found]"
 else
+   printf "\n"
    if check_installed curl; then
-      success_print "[curl] found."
+      success_printf "Checking to see if [curl] is installed..." "[curl] found."
    else
       install_pkg curl
    fi
@@ -225,19 +232,19 @@ else
 
    # install pre-requisites
    if check_installed gcc; then
-      success_print "[gcc] found."
+      success_printf "Checking to see if [gcc] is isntalled..." "[gcc] found."
    else
       install_pkg gcc
    fi
 
    if check_installed g++; then
-      success_print "[g++] found."
+      success_printf "Checking to see if [g++] is isntalled..." "[g++] found."
    else
       install_pkg g++
    fi
 
    if check_installed make; then
-      success_print "[make] found."
+      success_printf "Checking to see if [make] is isntalled..." "[make] found."
    else
       install_pkg make
    fi
@@ -247,27 +254,29 @@ fi
 
 # check if 'yarn' is installed, install if not
 if check_npm_installed yarn; then
-   success_print "[yarn] found."
+   success_printf "Checking to see if [yarn] is isntalled..." "[yarn] found."
 else
    install_npm_pkg yarn
 fi
 
 # check if 'git' is installed, install if not
 if check_installed git; then
-   success_print "[git] found."
+   success_printf "Checking to see if [git] is isntalled..." "[git] found."
 else
    install_pkg git
 fi
 
 # clone metaplex repo
-echo "cloning [metaplex] repo..."
-git clone https://github.com/metaplex-foundation/metaplex.git &>/dev/null
-check_cmd $?
-success_print "[metaplex] repo cloned successfully."
+if [ ! -d "${current_dir}/metaplex" ]; then # only clone if not already existing
+   printf "cloning [metaplex] repo..."
+   git clone https://github.com/metaplex-foundation/metaplex.git &>/dev/null
+   check_cmd $? "cloning [metaplex] repo..." "failed to clone [metaplex] repo."
+   success_printf "cloning [metaplex] repo..." "[metaplex] repo cloned successfully."
+fi
 
 # check if 'ts-node' installed, install if not
 if check_npm_installed ts-node; then
-   success_print "[ts-node] found."
+   success_printf "Checking to see if [ts-node] is isntalled..." "[ts-node] found."
 else
    install_npm_pkg ts-node
 fi
@@ -275,147 +284,104 @@ fi
 # check if solana is installed, install if not
 echo "Checking to see if [solana] installed..."
 if solana --version &>/dev/null; then
-   success_print "[solana] found."
+   success_printf "Checking to see if [solana] is isntalled..." "[solana] found."
 else
    warn_print "[solana] not found, installing..."
    sh -c "$(curl -sSfL https://release.solana.com/v1.8.0/install)"
+   check_cmd $? "[solana] not found, installing..." "failed to install [solana]"
    . ~/.profile # source .profile so PATH updates in current session
-   success_print "[solana] installed successfully."
+   success_printf "[solana] not found, installing..." "[solana] installed successfully."
 fi
 
 solana config set --url https://api.${network}.solana.com >/dev/null # set solana network
 check_cmd $?
-keyJSON="${HOME}/.config/solana/${network}.json"
+keyJSON="${HOME}/.config/solana/wallet.json"
 
-if [ "${pubkey}" = "new" ]; then # generate new wallet
-   pubkey=$(solana-keygen new --outfile $keyJSON | grep pubkey | cut -d' ' -f2)
-   check_cmd $?
-else  #import public wallet
-   echo "${orange}Note: You will need your recovery phrase to import wallet. This is required by Solana CLI
-      and will not be saved by this script nor on the system anywhere. The input is silent as well so no one can
-      see the input as you type it in or copy it!${normal}"
-   solana-keygen recover 'prompt://?key=0/0' --outfile $keyJSON
-   check_cmd $?
+if [ ! -f $keyJSON ]; then # only if keypair doesn't exist
+   if [ "${pubkey}" = "new" ]; then # generate new wallet
+      solana-keygen new --outfile $keyJSON > tmp.txt
+      check_cmd $?
+
+      pubkey=$(cat tmp.txt | grep pubkey | cut -d' ' -f2)
+      passphrase=$(cat tmp.txt | grep -A 1 recover | grep -v recover)
+
+      rm -f tmp.txt # remove file so seed phrase is not saved on system
+      echo "Save this seed phrase and your BIP39 passphrase to recover your new keypair: [${passphrase}]."
+      read -r -s -N 1 -p "Press [Enter] to continue..."
+   else  #import public wallet
+      echo "${orange}Note: You will need your recovery phrase to import wallet. This is required by Solana CLI and will not be saved by this script nor on the system anywhere. The input is silent as well so no one can see the input as you type it in or copy it!${normal}"
+      solana-keygen recover 'prompt://?key=0/0' --outfile $keyJSON
+      check_cmd $? "" "failed to import wallet."
+   fi
 fi
 
 solana config set --keypair $keyJSON >/dev/null # set Solana CLI to use wallet
 check_cmd $?
-success_print "set keypair"
+success_print "set keypair successfully."
 
 if [ "${network}" = "devnet" ]; then # only airdrop if running on devnet
    solana airdrop 1 >/dev/null #airdrop some SOL
-   check_cmd $?
-   success_print "airdropped 1 SOL"
+   check_cmd $? "" "airdrop to wallet failed."
+   success_print "airdropped 1 SOL."
 fi
 
 metaplex_dir="${current_dir}/metaplex"
 assets_dir="${current_dir}/assets"
 
-echo "Creating directory for images..."
-mkdir $assets_dir &>/dev/null # create directory for assests
-success_print "Directory created successfully."
-
-echo "${orange}**********************************************************************************************************************
-Pausing to allow time to upload images and JSON files to [${assets_dir}]. Refer to the README for further
-information on properly setting up your images and JSON files.
-**********************************************************************************************************************${normal}"
-read -r -s -N 1 -p "Press [Enter] to continue..." key
+if [ ! -d $assets_dir ]; then # only if directory doesn't exist
+   printf "Creating directory for images..."
+   mkdir $assets_dir &>/dev/null # create directory for assests
+   check_cmd "Creating directory for images..." "failed to create [$assets_dir}]."
+   success_printf "Creating directory for images..." "Directory [${assets_dir}] created successfully."
+fi
 
 js_dir="${metaplex_dir}/js"
 cd $js_dir
 
 echo "" # just adding an extra break in output
 echo "Installing node modules..."
-yarn install --silent # install required npm modules
-check_cmd $?
-success_print "Node modules installed successfully."
+yarn install --silent 2>${log_file} # install required npm modules
+check_cmd $? "Installing node modules..." "failed to install node modules."
+success_printf "Installing node moudles..." "Node modules installed successfully."
 
-echo "Building packages..."
-yarn build # build metaplex componenets (cli, web, etc)
-check_cmd $?
-success_print "Packages built successfully."
+echo "${orange}********************************************************************************************************************************************
+Pausing to allow time to upload images and JSON files to [${assets_dir}]. Refer to the README for further
+information on properly setting up your images and JSON files.
+}*******************************************************************************************************************************************${normal}"
+read -r -s -N 1 -p "Press [Enter] to continue..." key
 
-echo "Preparing packages and binaries..."
-yarn bootstrap
-check_cmd $?
-success_print "Packages and binaries prepared successfully"
-
-cd $metaplex_dir
+cd ${current_dir} # go back to starting location to save mint cache there
 cm_cli="${js_dir}/packages/cli/src/candy-machine-cli.ts"
 
-echo "Uploading images to candy machine..."
-cm_publickey=$(ts-node $cm_cli upload $assets_dir --env ${network} --keypair ${keyJSON} | grep publickey | cut -d' ' -f9)
-check_cmd $?
-success_print "Image upload successful."
+printf "Uploading images for candy machine..."
+ts-node $cm_cli upload $assets_dir --env ${network} --keypair ${keyJSON} 2>${log_file} 1>/dev/null
+check_cmd $? "Uploading images for candy machine..." "failed to upload images."
+success_printf "Uploading images for candy machine..." "Image upload successful."
 
-read -p "What would you like the price of the NFTs to be (in SOL): " price
+sol_price=$(curl https://www.coingecko.com/en/coins/solana 2>/dev/null | grep -oP '(?<=<span class="no-wrap" data-price-btc).*?(?=</span>)' | sed 's/[^>]*>//g' | sed -n '1p')
 
-echo "Creating candy machine..."
-cm_pubkey=$(ts-node $cm_cli create_candy_machine --env ${network} --keypair ${keyJSON} --price ${price} | grep pubkey | cut -d' ' -f6)
-check_cmd $?
-success_print "Candy machine created successfully."
+read -p "What would you like the price of the NFTs to be (in SOL [1 SOL currently ${sol_price} USD]): " price
+
+printf "Creating candy machine..."
+ts-node $cm_cli create_candy_machine --env ${network} --keypair ${keyJSON} --price ${price} 2>${log_file} 1>/dev/null
+check_cmd $? "Creating candy machine..." "failed to create candy machine."
+success_printf "Creating candy machine..." "Candy machine created successfully."
 
 start_of_today=`date '+%d %b %Y 00:00:00 %Z'`
-echo "Updating candy machine with available minting start date to [${start_of_today}]..."
-cm_timestamp=$(ts-node $cm_cli update_candy_machine --keypair ${keyJSON} --date "${start_of_today}" | grep startDate | cut -d' ' -f6)
-check_cmd $?
-success_print "Date updated successfully."
+printf "Updating candy machine with available minting start date to [${start_of_today}]..."
+ts-node $cm_cli update_candy_machine --env ${network} --keypair ${keyJSON} --date "${start_of_today}" 2>${log_file} 1>/dev/null
+check_cmd $? "Updating candy machine with available minting start date to [${start_of_today}]..." "failed to update candy machine."
+success_printf "Updating candy machine with available minting start date to [${start_of_today}]..." "Date updated successfully."
 
-cd ${current_dir}
+num_imgs=$(ls ${assests_dir}/*.png | wc -l) # get number of images in assets directory
+count=0 # used in progress print
 
-echo "Cloning [candy-machine-mint] repo..."
-git clone https://github.com/exiled-apes/candy-machine-mint.git &>/dev/null
-check_cmd $?
-success_print "[candy-machine-mint] cloned successfully."
-
-cmm_dir="${current_dir}/candy-machine-mint"
-
-cd $cmm_dir
-
-echo "Installing node modules..."
-yarn install --silent # install required npm modules
-check_cmd $?
-success_print "Node modules installed successfully."
-
-echo "Building packages..."
-yarn build # build metaplex componenets (cli, web, etc)
-check_cmd $?
-success_print "Packages built successfully."
-
-env_ex_file="${cmm_dir}/.env.example"
-env_file="${cmm_dir}/.env"
-
-if [ ! -f $env_file ]; then
-   echo "Setting up environment file..."
-   mv ${env_ex_file} ${env_file}
-   check_cmd $?
-
-   sed -ie "s/REACT_APP_CANDY_MACHINE_CONFIG=__PLACEHOLDER__/REACT_APP_CANDY_MACHINE_CONFIG=${cm_publickey}/" $env_file
-   check_cmd $?
-   sed -ie "s/REACT_APP_CANDY_MACHINE_ID=__PLACEHOLDER__/REACT_APP_CANDY_MACHINE_ID=${cm_pubkey}/" $env_file
-   check_cmd $?
-   sed -ie "s/REACT_APP_TREASURY_ADDRESS=__PLACEHOLDER__/REACT_APP_TREASURY_ADDRESS=${pubkey}/" $env_file
-   check_cmd $?
-   sed -ie "s/REACT_APP_CANDY_START_DATE=__PLACEHOLDER__/REACT_APP_CANDY_START_DATE=${cm_timestamp}/" $env_file
-   check_cmd $?
-   sed -ie "s/REACT_APP_SOLANA_NETWORK=devnet/REACT_APP_SOLANA_NETWORK=${network}/" $env_file
-   check_cmd $?
-   sed -ie "s|REACT_APP_SOLANA_RPC_HOST=https://explorer-api.devnet.solana.com|REACT_APP_SOLANA_RPC_HOST=https://explorer-api.${network}.solana.com|" $env_file # use something other than `/` to separate search and replace fields since `/` is in URL
-   check_cmd $?
-fi
-success_print "Environment file successfully setup."
-
-
-echo "${green}############################################################################################################################
-
-Configuration Complete! You may take the following steps to run the candy machine:
-
-   - upload image/json file combos to [${assets_dir}]
-      - be sure the image/json files have the same base file name and are zero
-        indexed, such as {0.png, 0.json}, {1.png, 1.json}, ... , {N.png, N.json}
-   - if on devnet, you may run 'solana airdrop N' to add money to your wallet for
-     minting, where `N` is a number >= 1 for the number of SOL to drop.
-   - cd to [${cmm_dir}] and then run 'yarn start' to test candy machine
-   ############################################################################################################################${normal}"
+for i in $(seq $num_images); do # mint images, one at a time
+   printf "\rMinting operation ongoing... successfully minted [${count}] of [${num_imgs}]"
+   ts-node $cm_cli mint_one_token -e ${network} -k ${keyJSON} 2>${log_file} 1>/dev/null
+   check_cmd $? "Minting operation ongoing... successfully minted [${count}] of [${num_imgs}]" "unable to mint image."
+   count=$((count+1))
+done
+success_print "\r[${count}] images successfully minted."
 
 exit 0 # normal exit
